
[namespace]
default = "ashwood"

[env]
account_address = "0x0785f4ffe231e0df381c83a16e9f8b696c21a1b492b93412f8c186a337e3cdb7"
private_key = ""
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[world]
seed = "ashwood_2"
name = "Ashwood"
description = "Become a manager"
cover_uri = "file://assets/bg.webp"
website = "https://ashwood.vercel.app/"


[writers]
"ashwood" = ["ashwood-actions","ashwood-armies","ashwood-battlefields","ashwood-units"]
